secrets:
    acme_email: ENC[AES256_GCM,data:iZsOFRK7SjKsTRhdeg==,iv:r3KuAV4pmK5PaJaf1xGvKhgQmd9MLApweMA00yV9Ix4=,tag:Bh2W8szPdxAK+ZOK3gHhBQ==,type:str]
sops:
    age:
        - recipient: age1al36hkk8can83zpxq8qyy07gpv83hdw9vchfly5f264kanz405as283a00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ2NCTkRaeDBteVlVNThR
            NHZCanlGbEQzSWJHamFlYm1EL0FoUHA2T0ZVCml3Q0d5STMvdW12T05SSFBtQlp5
            NlJvWWlzdzQ2Yno4VlZ2a3E5aDBmTmcKLS0tIDRoVDRPVHdoaWtaNTN6Q2xEZVV0
            YmVXZHlYQ0cyNHRGNWhqaFhBVWh5Z3MKVDfBqNALhLHxkvcZGWVmUPDm47BlQdvq
            4gHvz0HqSNwRyO9c5wAfYQooim0EQiZ287scRBq26XQUPPg/yrFyng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdERDaTlHUW9VQjZIR1ZW
            M2hZWG9GNkM5Z3BVMk9Lelh5cUZON2JxNmlZCk5QamtYT1l3a0xuU0h1MC9jZVdu
            ZTBNaGJyUGhlUk1iVG5maDMwdWZyelEKLS0tIExUcWRISlRpcXJ3MzMxeld5andR
            NkxMUkJXN1NXeHVSK1JabVlxUWZXMG8Ke22wJwH1JCoNNfKoLhSLlELKk6AxJ7UM
            cMFEmAezTjU0gmVx2XWxCr3/VapT4CZJjhI7I3WKFk7M/WkXrT75yA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYUhQdEdZYUp4SHFwUGlX
            eHg4aXNhcVRNaVkwRnlFV040eUtESk44cVdnCkVNb1k4Q0g0UmpueW5haHhGN3Iy
            N1FSMnVReEJmQjA2ZlA2R2x5MDFZZGMKLS0tIGR0Tk80UmZwRWxVczB0WDJ5QTdZ
            bFErZnA5bitIOGFpb3JOeXZYSE9SeW8K5JEpMu7iuqVcQGdz5KsfmBSyS1lPWio+
            9icW7NSvZhpdIwse8t4pwlz8H6DNRkj5UoovXx23laKW2QO8rO+E5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15arcg8x6ltnsacwalvny0h2d4d4wkdmax328mw3v5vda9zm97uqshtavmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bGFrVEZPSUtUa0oyWG50
            dmNxcjFBUWxKdFJyeENxY2I2QWY5WDdySDMwClN1c1ZNcmo5OFl6bXRFVlhlb3Av
            czNvZjEwRjZhNkRsZVEreUFuQitsT2sKLS0tIHhVWHY4REtaZ2l0T2FFNzE3Z05T
            Q0RRTW1YcEl4QXpESW1Yem9TZ0VsUE0KaZxIKqof6eUCfgfZy3T1aEtB6M3VjZ9e
            xPGQ7OD9jvbDLAbnQ31oIKuG73fQ7suMfVMY2pEo3NlhCpkQoN4+Eg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1khw2eps099audp3uu5s9rk07qznllh5c8a43gv5dtpnq2a7lue6qrehn5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOTVyMGdGdUQ0Z2NVVHFZ
            RytCU0FmYk9XTWR4aytSYUpkMWN2c0MxcFZBCjAwdFZCWFFlUWp2RThOOVMyTlpT
            b1FsazJlRDFrNDdmalc2aTBmZ3h3cDAKLS0tIGU5MFAxcEwvem9ZVktkQU5PeTBa
            aHlCWkZ0OWRkdktXQ2x4VmhyV0pDZ3MK7I2c6a2RUnG/spY8xdqxpC+nMUzUx5+I
            HQ9fV2D4OJ64aSp7O4FPkBhYLW1lrpS3nFTZn2yTw+1zQEK7sdBuxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6mzqe0cejajzt0c7nwdjz4xvs4hjct9d8hrgj60e7unzyfd7prsn0npe5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5R2pQY3kvRVUvaDRCME9I
            c09NMENoRkZIUTdhcStGbENEVXJPNXQ5QnhvCm9GdHAyRmxQLzltZmlhRHRxZ2d4
            RjRCakhQS2R2NmQ2emdGVmRaZDFqb3MKLS0tIFJBMTR1bVJFcDNqUjNTek5teWVw
            N1Q1UFdFc2M4YWk2WE50VWJHM3NKM3cK5k8/k+3sP4hwNf3Abbn3/ROoCBvgjlX1
            1a9RvJrAL9Q1nYcTFDsxpSRYHJbGVXm5lfJEclaRIt8xVFiLsn0COA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t0ufylv5xfwhmcamu4gpwtay4wcuyqgzlkht4t04s9qjl8xjks9skxrt02
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d1pWN1RXSXkvS0FYc3lL
            QU9FcXhVMWhRZmJ6WFR1MkdKTUdtRndEY1c0CnFxYTcvcDVQdW1pSlpsdkZoYTV4
            cHVIcGN2VWxmdHNJV2ZCOHgvSmVYb1kKLS0tIEVETE8zemE4MTdQSVIxNzVIWW1k
            TC93NjdJZU5uUXh6ZUs2ZHNGaW9FVncKS31S5+rt7FQZNm+ByIwgb2uVv66/BdZZ
            zk3Fgm7C22stAUSFu7qxJUR545sifdISXlkc4rFZjnsgMzXY1LJBbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T11:16:45Z"
    mac: ENC[AES256_GCM,data:CuSe/yp0SeMYSJ0rUudHvWhs6DBref++uI+U3RgCRc0mk7NUtRMSSgJKs/cJrEV59mgfIYS2/CQ+dEWMTs34oHd3sgvXAhfRg1FKN9+SHJiHXKIv0+qGqw1PUeZwn1gEwj6gdu585v510M1eyyIM+2ve/BumjzrAvclOoOs9NVs=,iv:qUp52WhgZlWyX9IzTWDgNVAWVzZ9/ASipzH3dOrKbSc=,tag:e/L13iqJAKkkdf0B9xDdew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
